package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Gabriel Schmidt Cordeiro <gabrielscordeiro2012@gmail.com>
 */
public class ViewConsultaCurriculo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewConsultaCurriculo
     */
    public ViewConsultaCurriculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        scrollTabelaCurriculos = new javax.swing.JScrollPane();
        tabelaCurriculos = new javax.swing.JTable();

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciar Currículos");
        setMinimumSize(new java.awt.Dimension(470, 490));
        setPreferredSize(new java.awt.Dimension(470, 490));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnAdicionar.setText("Adicionar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(btnAdicionar, gridBagConstraints);

        btnEditar.setText("Editar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(btnEditar, gridBagConstraints);

        btnExcluir.setText("Excluir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(btnExcluir, gridBagConstraints);

        scrollTabelaCurriculos.setWheelScrollingEnabled(false);

        tabelaCurriculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaCurriculos.setColumnSelectionAllowed(true);
        tabelaCurriculos.setFillsViewportHeight(true);
        scrollTabelaCurriculos.setViewportView(tabelaCurriculos);
        tabelaCurriculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(scrollTabelaCurriculos, gridBagConstraints);

        getAccessibleContext().setAccessibleName("Gerenciar Currículos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Action Listeners */
    public void addActionListenerAcaoAdicionar(ActionListener listener) {
        btnAdicionar.addActionListener(listener);
    }

    public void addActionListenerAcaoEditar(ActionListener listener) {
        btnEditar.addActionListener(listener);
    }

    public void addActionListenerAcaoExcluir(ActionListener listener) {
        btnExcluir.addActionListener(listener);
    }

    /* GETTERS AND SETTERS */
    public JButton getBtnAdicionar() {
        return btnAdicionar;
    }

    public void setBtnAdicionar(JButton btnAdicionar) {
        this.btnAdicionar = btnAdicionar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    public JRadioButton getjRadioButton1() {
        return jRadioButton1;
    }

    public void setjRadioButton1(JRadioButton jRadioButton1) {
        this.jRadioButton1 = jRadioButton1;
    }

    public JScrollPane getScrollTabelaCurriculos() {
        return scrollTabelaCurriculos;
    }

    public void setScrollTabelaCurriculos(JScrollPane scrollTabelaCurriculos) {
        this.scrollTabelaCurriculos = scrollTabelaCurriculos;
    }

    public JTable getTabelaCurriculos() {
        return tabelaCurriculos;
    }

    public void setTabelaCurriculos(JTable tabelaCurriculos) {
        this.tabelaCurriculos = tabelaCurriculos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane scrollTabelaCurriculos;
    private javax.swing.JTable tabelaCurriculos;
    // End of variables declaration//GEN-END:variables
}
