/*
 * Copyright (C) 2017 Gabriel Batista Alves <Gabrieltanasia at bitbucket.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Gabriel Batista Alves <Gabrieltanasia at bitbucket.org>
 */
public class ViewConsultaCandidato extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewConsultaCandidato
     */
    public ViewConsultaCandidato() {
        initComponents();
        btnSelecionar.setVisible(false);
    }

    /**
     * Creates new form ViewConsultaCandidato
     */
    public ViewConsultaCandidato(boolean externo) {
        initComponents();
        btnSelecionar.setVisible(externo);
        btnAdicionar.setVisible(!externo);
        btnExcluir.setVisible(!externo);
        btnEditar.setVisible(!externo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        scrollTabelaCandidatos = new javax.swing.JScrollPane();
        tabelaCandidatos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciar Candidatos");
        setPreferredSize(new java.awt.Dimension(470, 490));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnAdicionar.setText("Adicionar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(btnAdicionar, gridBagConstraints);

        btnEditar.setText("Editar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(btnEditar, gridBagConstraints);

        btnExcluir.setText("Excluir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(btnExcluir, gridBagConstraints);

        btnSelecionar.setText("Selecionar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        getContentPane().add(btnSelecionar, gridBagConstraints);

        scrollTabelaCandidatos.setWheelScrollingEnabled(false);

        tabelaCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaCandidatos.setColumnSelectionAllowed(true);
        scrollTabelaCandidatos.setViewportView(tabelaCandidatos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 433;
        gridBagConstraints.ipady = 379;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(scrollTabelaCandidatos, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Action Listeners */
    public void addActionListenerAcaoAdicionar(ActionListener listener) {
        btnAdicionar.addActionListener(listener);
    }

    public void addActionListenerAcaoEditar(ActionListener listener) {
        btnEditar.addActionListener(listener);
    }

    public void addActionListenerAcaoExcluir(ActionListener listener) {
        btnExcluir.addActionListener(listener);
    }

    public void addActionListenerAcaoSelecionar(ActionListener listener) {
        btnSelecionar.addActionListener(listener);
    }

    public void resetActionListenerAcaoSelecionar() {
        ActionListener[] actions = btnSelecionar.getActionListeners();
        for (int i = 0; i < actions.length; i++) {
            btnSelecionar.removeActionListener(actions[i]);
        }
    }

    public JButton getBtnAdicionar() {
        return btnAdicionar;
    }

    public void setBtnAdicionar(JButton btnAdicionar) {
        this.btnAdicionar = btnAdicionar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    public JTable getTabelaCandidatos() {
        return tabelaCandidatos;
    }

    public void setTabelaCandidatos(JTable tabelaCandidatos) {
        this.tabelaCandidatos = tabelaCandidatos;
    }

    public JScrollPane getScrollTabelaCandidatos() {
        return scrollTabelaCandidatos;
    }

    public void setScrollTabelaCandidatos(JScrollPane scrollTabelaCandidatos) {
        this.scrollTabelaCandidatos = scrollTabelaCandidatos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JScrollPane scrollTabelaCandidatos;
    private javax.swing.JTable tabelaCandidatos;
    // End of variables declaration//GEN-END:variables
}
