/*
 * Copyright (C) 2017 Andre Luis Zipf <andrezipf94 at gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Andre Luis Zipf <andrezipf94 at gmail.com>
 */
public class ViewConsultaVaga extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewConsultaVagas
     */
    public ViewConsultaVaga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        scrollTabelaVagas = new javax.swing.JScrollPane();
        tabelaVagas = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciar Vagas");
        setMinimumSize(new java.awt.Dimension(470, 490));
        setPreferredSize(new java.awt.Dimension(470, 490));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnAdicionar.setText("Adicionar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(btnAdicionar, gridBagConstraints);

        btnEditar.setText("Editar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(btnEditar, gridBagConstraints);

        btnExcluir.setText("Excluir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(btnExcluir, gridBagConstraints);

        scrollTabelaVagas.setWheelScrollingEnabled(false);

        tabelaVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaVagas.setColumnSelectionAllowed(true);
        tabelaVagas.setFillsViewportHeight(true);
        scrollTabelaVagas.setViewportView(tabelaVagas);
        tabelaVagas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(scrollTabelaVagas, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* Action Listeners */
    public void addActionListenerAcaoAdicionar(ActionListener listener) {
        btnAdicionar.addActionListener(listener);
    }

    public void addActionListenerAcaoEditar(ActionListener listener) {
        btnEditar.addActionListener(listener);
    }

    public void addActionListenerAcaoExcluir(ActionListener listener) {
        btnExcluir.addActionListener(listener);
    }

    /* GETTERS AND SETTERS */
    public JButton getBtnAdicionar() {
        return btnAdicionar;
    }

    public void setBtnAdicionar(JButton btnAdicionar) {
        this.btnAdicionar = btnAdicionar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }

    public JScrollPane getScrollTabelaVagas() {
        return scrollTabelaVagas;
    }

    public void setScrollTabelaVagas(JScrollPane scrollTabelaVagas) {
        this.scrollTabelaVagas = scrollTabelaVagas;
    }

    public JTable getTabelaVagas() {
        return tabelaVagas;
    }

    public void setTabelaVagas(JTable tabelaVagas) {
        this.tabelaVagas = tabelaVagas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane scrollTabelaVagas;
    private javax.swing.JTable tabelaVagas;
    // End of variables declaration//GEN-END:variables
}
